name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get TLAPS
      run: wget -q https://github.com/tlaplus/tlapm/releases/download/1.6.0-pre/tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
    - name: Install TLAPS
      run: tar -xzf tlapm-1.6.0-pre-x86_64-linux-gnu.tar.gz
    - name: Run TLAPS
      run: tlapm/bin/tlapm --cleanfp -I tlapm/ tlaplus/BlockingQueue.tla
